from flask_app import db
# class wine_data(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     country = db.Column(db.String(120), index=True)
#     description = db.Column(db.String(120), index=True)
#     designation = db.Column(db.String(120), index=True)
#     points= db.Column(db.Integer,index=True)
#     province= db.Column(db.String(120), index=True)
#     region_1= db.Column(db.String(120), index=True)
#     region_2=db.Column(db.String(120), index=True)
#     taster_name=db.Column(db.String(120), index=True)
#     title=db.Column(db.String(120), index=True)
#     variety=db.Column(db.String(120), index=True)
#     winery=db.Column(db.String(120), index=True)
#     year= db.Column(db.Integer, index=True)
#     unique_names=db.Column(db.String(120), index=True)
#     index=db.Column(db.Integer, index=True)


# class wine_process(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     country = db.Column(db.String(120), index=True)
#     description = db.Column(db.String(120), index=True)
#     designation = db.Column(db.String(120), index=True)
#     points= db.Column(db.Integer,index=True)
#     province= db.Column(db.String(120), index=True)
#     region_1= db.Column(db.String(120), index=True)
#     region_2=db.Column(db.String(120), index=True)
#     taster_name=db.Column(db.String(120), index=True)
#     title=db.Column(db.String(120), index=True)
#     variety=db.Column(db.String(120), index=True)
#     winery=db.Column(db.String(120), index=True)
#     year= db.Column(db.Integer, index=True)
#     unique_names=db.Column(db.String(120), index=True)
#     index=db.Column(db.Integer, index=True)

#db.create_all()
